deploy:
  common:
    project_type: rails3 | silverstripe3 | drupal | php | sinatra
    base_dir: /var/www
    repository: git@gitlab.....
    project_slug: tradespot
    default_branch: master
    domain: domain.com
    user: root
    port: 22
  environments:
    development:
    staging:
      domain: staging.domain.com
      default_branch: master
    production:
      domain: production.domain.com
      default_branch: stable
dbs:
  default:
    development:
      name: project_development
      user: project_development
      pass:
      host: localhost
      port: 3306
    staging:
      name: project_staging
      user: project_staging
      pass: passw0rd
      host: localhost
      port: 3306    
    production:
      name: project_production
      user: project_production
      pass: passw0rd
      host: localhost
      port: 3306    
backup:
  local:
    keep:2
  ftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
  sftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
  s3:
    keep: 10
    key: key
    secret: secret
    bucket: bucket
mail:
  smtp:
    development:
    staging:
    production:
      default_from:
        name: dev
        email: dev@domain.com
      server: smtp.gmail.com
      authenticate: true
      user: username@domain.com
      pass: passw0rd
      secure: tls
      charset_encoding: utf-8
      port: 587
apache:
  development:
  staging:
    server_name: staging.domain.com
    server_aliases:
      - www.staging.domain.com
    env_vars:
      RAILS_ENV: staging
      APPLICATION_ENV: staging
  production:
    server_name: production.domain.com
    server_aliases:
      - www.production.domain.com
    server_admin: dev@domain.com
    env_vars:
      RAILS_ENV: production
      APPLICATION_ENV: production
chown:
  development:
  staging:
    -
      path: public/uploads
      user: www-data  
  production:
    -
      path: public/uploads
      user: www-data
chmod:
  development:
  staging:
    -
      path: public/uploads
      mode: 775  
  production:
    -
      path: public/uploads
      mode: 775
chgrp:
  development:
  staging:
    -
      path: public/uploads
      group: www-data  
  production:
    -
      path: public/uploads
      group: www-data
resources:
  - public/assets
  - public/uploads
watch:
  sass:
    -
      src: public/assets/scss
      dest: public/assets/css
      filter: !ruby/regexp '/^.+\.scss$/'
  coffee:
    -
      src: public/assets/coffee
      dest: public/assets/js
      filter: !ruby/regexp '/^.+\.coffee$/'
log_dirs:
  - log