deploy:
  common:
    project_type:
    base_dir: /var/www
    repository: git@gitlab.....
    project_slug: tradespot
    default_branch: master
    domain: domain.com
    user: root
    port: 22
  environments:
    development:
    staging:
      domain: staging.domain.com
    production:
      domain: production.cdomain.com
dbs:
  default:
    development:
    staging:
    production:
backup:
  local:
    keep:2
  ftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
apache:
  development:
  staging:
    server_name: staging.domain.com
    server_aliases:
      - www.staging.domain.com
    env_vars:
      SS_ENVIRONMENT_TYPE: test
      RAILS_ENV: staging
      APPLICATION_ENV: staging
  production:
    server_name: production.domain.com
    server_aliases:
      - www.production.domain.com
    server_admin: dev@domain.com
    env_vars:
      SS_ENVIRONMENT_TYPE: live
      RAILS_ENV: production
      APPLICATION_ENV: production
resources:
permissions:
  development:
  staging:
    www_executable:
      - vendor/bin
  production:
    www_executable:
      - vendor/bin  
log_dirs:
  - log