deploy:
  common:
    project_type: rails3 | silverstripe3 | drupal | php | sinatra
    base_dir: /var/www
    repository: git@gitlab.....
    project_slug: tradespot
    default_branch: master
    domain: domain.com
    user: root
    port: 22
  environments:
    development:
    staging:
      domain: staging.domain.com
      default_branch: master
    production:
      domain: production.domain.com
      default_branch: stable
dbs:
  default:
    development:
      user: root
      pass:
      host: localhost
      port: 3306
    staging:
      user: staging_db
      pass: passw0rd
      host: localhost
      port: 3306    
    production:
      user: production_db
      pass: passw0rd
      host: localhost
      port: 3306    
backup:
  local:
    keep:2
  ftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
  sftp:
    keep: 10
    host: backup-host.com
    user: remote_backup
    pass: passw0rd
  s3:
    keep: 10
    key: key
    secret: secret
    bucket: bucket
apache:
  development:
  staging:
    server_name: staging.domain.com
    server_aliases:
      - www.staging.domain.com
    env_vars:
      SS_ENVIRONMENT_TYPE: test
      RAILS_ENV: staging
      APPLICATION_ENV: staging
  production:
    server_name: production.domain.com
    server_aliases:
      - www.production.domain.com
    server_admin: dev@domain.com
    env_vars:
      SS_ENVIRONMENT_TYPE: live
      RAILS_ENV: production
      APPLICATION_ENV: production
chown:
  development:
  staging:
  production:
    -
      path: public/uploads
      user: www-data
chmod:
  development:
  staging:
  production:
    -
      path: public/uploads
      mode: 775
chgrp:
  development:
  staging:
  production:
    -
      path: public/uploads
      group: www-data
resources:
  - public/assets
  - public/uploads
log_dirs:
  - log